### ISSUE TITLE
2022.01.21 최중재

### ISSUE THREAD

**Issue by joong8812** [joneheart/3_team_study#6]
- [x]  `Django 기초반` 4주차 완강
- [x] TIL 작성
- [x] `CodeUp`-[Python 기초 100제](https://codeup.kr/problemsetsol.php?psid=33) 최소 5문제 풀기 
- [x] `NomadCoders`-[바닐라 JS로 크롬 앱 만들기](https://nomadcoders.co/javascript-for-beginners/lobby) 최소 2강 듣기
- [x]  `깃허브 리드미 꾸미기 가이드` 미니튜터 강의 듣기 at 4:30 P.M

**Comment by iamdoerchoi** [comment]
Codeup - solve solve 6057 to 6084 (28)

**Comment by iamdoerchoi** [comment]
NomadCoder - 2강 :)
